version: "2"
services:
   # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.87.0
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./collector.yaml:/etc/otel-collector-config.yaml 
      - shared_volume:/logs         

    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP Http receiver
         
  genexusapp:
    image: mkshimao/opentelemetryjavasqlserver:latest
    depends_on:
      - otel-collector
    volumes:
      - shared_volume:/logs
          
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_RESOURCE_ATTRIBUTES=service.namespace=GeneXus,service.name=TesteOpenTelemetry,service.version=1.0.0
      - OTEL_METRICS_EXPORTER=otlp   
      - OTEL_LOGS_EXPORTER=otlp
      - GX_LOG_LEVEL=debug
      - GX_LOG_LEVEL_USER=debug
      - GX_LOG_OUTPUT=ConsoleAppender

    ports:
      - "8888:8080"

volumes:
  shared_volume: